# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Build matrix options
matrix:
  include:
    - php: 7.2
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true
  
# Script, failures in this section will result in build status 'failed'
script: 
  - phpunit --configuration test/travis.phpunit.xml.dist
  - phpunit --configuration test/phpunit.xml
